apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-blog-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: simple-blog-api
          image: sruthibk43/simple_blog_api_ts-master
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
                memory: "512Mi"
                cpu: "500m"
          env:	
            - name: PGUSER	
              value: postgres	
            - name: PGHOST
              value: postgres-cluster-ip-service	
            - name: PGPORT	
              value: '5432'	
            - name: PGDATABASE	
              value: postgres	
            - name: PGPASSWORD	
              valueFrom:	
                secretKeyRef:	
                  name: pgpassword	
                  key: POSTGRES_PASSWORD
              