apiVersion: v1
kind: Service
metadata:
    name: client-node-port
spec:
    selector:
      component: web
    type: NodePort
    ports:
        - port:  3000
          targetPort: 3000
          nodePort: 31515
    
        
