version: '3'
services:
 redis_db:
   image: "redis"
   volume:
     - ./data:/data
     - containerPath:ro
   command: ["redis-server", "--save", "1 1"]
 node_app:
   build: ./
   image: "sruthibk43/visits"
   ports:
     - "8081:8081"